class AppRoutes {
  AppRoutes._();

  static const splash = '/splash';
  static const welcome = '/welcome';
  static const partnerBenefits = '/partner-benefits';
  static const otp = '/otp';
  static const otpVerification = '/otp/verify';
  static const setPassword = '/set-password';
  static const personalInfo = '/registration/personal-info';
  static const address = '/registration/address';
  static const kyc = '/registration/kyc';
  static const vehicleRegistration = '/registration/vehicle';
  static const emergencyContact = '/registration/emergency-contact';
  static const review = '/registration/review';
  static const vehicleSelection = '/registration/vehicle-selection';
  static const vehicleDetails = '/registration/vehicle-details';
  static const deliveryZone = '/registration/delivery-zone';
  static const documentUpload = '/documents';
  static const selfieVerification = '/registration/selfie-verification';
  static const welcomeKit = '/registration/welcome-kit';
  static const applicationSubmitted = '/registration/application-submitted';
  static const bankDetails = '/bank-details';
  static const verificationStatus = '/verification-status';
  static const training = '/training';
  static const agreement = '/agreement';
  static const approval = '/approval';
  static const dashboard = '/dashboard';
  static const earnings = '/earnings';
  static const orders = '/orders';
  static const incomingOffer = '/orders/offer';
  static const activeOrder = '/orders/active';
  static const orderDetails = '/orders/details';
  static const wallet = '/wallet';
  static const support = '/support';
  static const profile = '/profile';
  static const manageVehicleDetails = '/profile/vehicle-details';
  static const manageDocuments = '/profile/documents';
  static const notifications = '/notifications';
  static const settings = '/settings';
}
